In [6]:
%run '00_database_connectivity_setup.ipynb'

          x         y
0  0.060658  0.967170
1  0.706408  0.305432
2  0.286925  0.400344
3  0.015306  0.776081
4  0.514513  0.323713
5  0.553623  0.089694

In [7]:
%%execsql
DROP TABLE IF EXISTS  felipe.bic_azeqnotif00_sum

In [8]:
%%showsql
select madlib.summary('sap_bi.bic_azeqnotif00_int', 'felipe.bic_azeqnotif00_sum');

                                         summary
0  (felipe.bic_azeqnotif00_sum,17,108.878752947)

In [9]:
%%execsql

CREATE OR REPLACE FUNCTION my_to_date(text, text) RETURNS date AS $$

BEGIN
    IF to_number($1,'99999999') = 0 THEN
        RETURN null;
    ELSE 
        RETURN to_date($1, $2);
    END IF;
END;

$$ LANGUAGE plpgsql

In [10]:
%%showsql
select target_column, distinct_values, missing_values, blank_values, min, max, most_frequent_values
from felipe.bic_azeqnotif00_sum
where fraction_blank < 0.999 and distinct_values > 1;

,target_column,distinct_values,missing_values,blank_values,min,max,most_frequent_values
0,notificatn,950805,0,0,12.0,12.0,"[000200477794, 000300529260, 000200481056, 000300529835, 000300529050, 000300528304, 000300528943, 000300528662, 000300528888, 000400051648]"
1,recordmode,2,0,1607,0.0,1.0,"[N, ]"
2,equipment,128908,0,522846,0.0,18.0,"[, 000000000010658053, 000000000010184434, 000000000010322747, 000000000010000667, 000000000010148268, 000000000010078336, 000000000010144483, 000000000010297644, 000000000010176945]"
3,ucserialnr,106363,0,529650,0.0,18.0,"[, 000000000000000001, 000000000000000002, 000000000000000003, 000000000000000004, 000000000000000005, 000000000000000006, 000000000000000007, 000000000000000008, 000000000000000009]"
4,material,130312,0,67684,0.0,18.0,"[, QA-SYSTEM, HES-ISSUE, QUALITY SYSTEMS, P205799, 000000000003807249, P206128, 18-920-138, 000000000007200920, DUMMY]"
5,createdon,5835,0,0,8.0,8.0,"[20061113, 20050412, 20071030, 20150611, 20040727, 20090923, 20150604, 20140519, 20160113, 20111221]"
6,crea_time,77905,0,0,6.0,6.0,"[222117, 151510, 124708, 180859, 084336, 094744, 104533, 205729, 093459, 153244]"
7,not_type,29,0,0,2.0,2.0,"[S3, ZF, S2, ZD, ZC, S1, MP, ZE, ZB, M3]"
8,maintplant,45,0,541331,0.0,4.0,"[, KOS2, HCS0, EWHG, EWWD, FKIA, EWAA, MYLB, EWNS, 4026]"
9,bic_zcatprof,14,0,0,9.0,9.0,"[S10000001, QI0000001, QD0000001, QC0000001, MP0000010, 000000001, QE0000001, QM0000001, QB0000001, QH0000001]"
10,bic_zartpr,6,0,0,2.0,2.0,"[QM, SM, MP, PM, Z4, SD]"
11,priority,6,0,109996,0.0,1.0,"[3, 2, 4, 1, , 5]"
12,bic_ziloan,999959,0,0,12.0,12.0,"[000010453729, 000010463710, 000010464385, 000010430535, 000010426409, 000010469466, 000010463713, 000010468279, 000010461447, 000010469194]"
13,createdby,6242,0,0,3.0,12.0,"[EVENSEN, WF-BATCH, WALKERK, BACKGROUND, LUNDKAM, BROYLEM, KOSTRBJ, KOSMKA, BANASZU, SALAZAA1]"
14,bic_zequihist,950805,0,0,12.0,12.0,"[000200477794, 000300529260, 000200481056, 000300529835, 000300529050, 000300528304, 000300528943, 000300528662, 000300528888, 000400051648]"
15,plant,115,0,83929,0.0,4.0,"[KOS2, EWHG, , KOS1, HCS0, EWSC, 4024, EWWD, 5100, GSEA]"

In [13]:
%%showsql
select notificatn, recordmode, equipment, material, my_to_date(createdon, 'YYYYMMDD') as createdon, not_type, maintplant,
bic_zcatprof, priority,  bic_zartpr, bic_ziloan, bic_zequihist, plant
from sap_bi.bic_azeqnotif00_int limit 10

,notificatn,recordmode,equipment,material,createdon,not_type,maintplant,bic_zcatprof,priority,bic_zartpr,bic_ziloan,bic_zequihist,plant
0,000200304463,N,,,2013-02-13,ZF,,QI0000001,3,QM,000006515778,000200304463,KOS2
1,000200441991,N,,P104047-0003,2015-05-12,ZD,,QD0000001,3,QM,000009681313,000200441991,KOS2
2,000200190596,N,,000000000200007240,2010-12-30,ZD,,QD0000001,3,QM,000003734736,000200190596,KOS2
3,000200190649,N,,QA-SYSTEM,2011-01-03,ZD,,QD0000001,3,QM,000003736353,000200190649,KOS2
4,000200191560,N,,000000000200029247,2011-01-11,ZF,,QI0000001,3,QM,000003755049,000200191560,KOS2
5,000200193167,N,,QA-SYSTEM,2011-01-26,ZD,,QD0000001,3,QM,000003789064,000200193167,KOS2
6,000200194033,N,,P103583-0012,2011-02-02,ZD,,QD0000001,3,QM,000003808374,000200194033,KOS2
7,000200194035,N,,P103583-0012,2011-02-02,ZD,,QD0000001,3,QM,000003808376,000200194035,KOS2
8,000200194036,N,,P103583-0012,2011-02-02,ZD,,QD0000001,3,QM,000003808415,000200194036,KOS2
9,000200194828,N,,18-208-409,2011-02-09,ZD,,QD0000001,3,QM,000003823105,000200194828,KOS2