In [7]:
%run '00_database_connectivity_setup.ipynb'

          x         y
0  0.489855  0.573534
1  0.490041  0.320402
2  0.836111  0.481961
3  0.492016  0.305475
4  0.844573  0.987999
5  0.763850  0.494735

In [2]:
%%execsql
DROP TABLE IF EXISTS  felipe.bic_azqn_o30400_sum

In [3]:
%%showsql
select madlib.summary('sap_bi.bic_azqn_o30400_int', 'felipe.bic_azqn_o30400_sum');

                                         summary
0  (felipe.bic_azqn_o30400_sum,55,174.315740108)

In [5]:
%%showsql
select target_column, distinct_values, missing_values, blank_values, min, max, most_frequent_values
from felipe.bic_azqn_o30400_sum
where fraction_blank < 0.999 and distinct_values > 1;

,target_column,distinct_values,missing_values,blank_values,min,max,most_frequent_values
0,notificatn,412967,0,0,12.0,12.0,"[000200474299, 000200481530, 000200481154, 000200480126, 000200481744, 000200405658, 000200479795, 000200478801, 000200460685, 000200481909]"
1,nfcat_code,81,0,1480,0.0,4.0,"[0010, 0040, 0020, 0060, 0030, 0090, 0050, 0070, Q210, Q330]"
2,nfcat_type,2,0,1480,0.0,1.0,"[D, ]"
3,nfcat_grp,223,0,1480,0.0,8.0,"[QI000015, QD000015, QC000021, QC000011, QC000016, QE000015, QB000010, QD000020, QC000031, QE000020]"
4,purch_org,34,0,224295,0.0,4.0,"[, KOS1, EWSC, EWHG, EWBO, EFST, GSEA, EWHP, EWMC, EWC1]"
5,vendor,3713,0,207973,0.0,10.0,"[, 0000001609, 0000002430, 0000100650, 0000004001, 0000101204, 0000101966, 0000123898, 0000108705, 0000108766]"
6,salesorg,29,0,439283,0.0,4.0,"[, KOS2, EWC1, EFST, FKIA, KOS1, EERO, EWHG, FKM1, EWSC]"
7,distr_chan,3,0,439323,0.0,2.0,"[, 01, 02]"
8,division,9,0,439323,0.0,2.0,"[, 01, FL, PP, NV, WS, VB, 02, RM]"
9,customer,951,0,434264,0.0,10.0,"[, 0000045036, 0000046932, 0000000024, 0000045066, 0000055084, 0000045011, 0000046822, 0000046951, 0000046956]"
10,funct_loc,296,0,444465,0.0,30.0,"[, C-CD-STAD-ST004, C-VD-CCBD-CC001-A0002, C-CD-STAD-ST007, C-CD-STAD-ST014, C-CD-STAD-ST010, H-AM-RSCH, C-CA-PTBA-ST004, AZURIT_M_PSUD-AZTP, C-CD-STAD-ST007-GFT02-E_04H]"
11,equipment,46574,0,376815,0.0,18.0,"[, 000000000011862334, 000000000012104914, 000000000010071559, 000000000011104979, 000000000012299532, 000000000011783150, 000000000010002682, 000000000010760230, 000000000011248473]"
12,material,111373,0,2051,0.0,18.0,"[QA-SYSTEM, QUALITY SYSTEMS, DUMMY, , NON FMC PART, P206733, P1000023500, P207236, P206740, FKM-QA-SYSTEM]"
13,plant,112,0,6731,0.0,4.0,"[KOS1, EWSC, EWHG, 4024, 5100, GSEA, 4011, KOS2, MYGF, 7500]"
14,storno,2,0,442492,0.0,1.0,"[, R]"
15,notif_orgn,3,0,0,2.0,2.0,"[Q2, Q3, Q1]"
16,bic_cqncpldat,5448,0,0,8.0,8.0,"[00000000, 20130925, 20120312, 20150312, 20141013, 20130603, 20140808, 20111104, 20130305, 20140611]"
17,oi_ebeln,108692,0,227707,0.0,10.0,"[, 0045353823, 0047841716, 0047572506, 0045285648, 0047873818, E602581, 0045517788, 0047859172, 0047314828]"
18,oi_ebelp,534,0,0,5.0,5.0,"[00000, 00001, 00002, 00010, 00003, 00004, 00020, 00005, 00006, 00030]"
19,not_type,14,0,0,2.0,2.0,"[ZF, ZC, ZD, ZE, ZB, Q2, Q3, Q1, ZO, ZN]"
20,base_uom,24,0,2104,0.0,3.0,"[EA, PCE, IN, , M, FT, ST, MM, CM, L]"
21,rstt_ftime,68225,0,0,6.0,6.0,"[000000, 135811, 162230, 080540, 114438, 061005, 112210, 090216, 145948, 131440]"
22,recordmode,2,0,19491,0.0,1.0,"[N, ]"
23,tctlstchg,217,0,0,14.0,14.0,"[20151115065533, 20151115065540, 20151115065546, 20160120005022, 20160126165647, 20160128164811, 20160121164734, 20160119164539, 20160120164709, 20160127164628]"
24,bic_zprodord,66763,0,340838,0.0,12.0,"[, 000300776294, 000300844636, 000300614231, 000300844637, 000300464111, 000300564797, 000300321842, 000300068915, 000300409393]"
25,createdby,5238,0,0,3.0,12.0,"[WF-BATCH, GRANTL, SALLEHMI, SALAZAA1, MCINTRA, WILLIAD1, HARDIEF, LUCASSY, PALAMAM, MCINTOC]"
26,changedby,4120,0,5228,0.0,11.0,"[GRANTL, SALLEHMI, SUGGSD, MCCALLM1, CHARLOTT, , CARNEIM, GILLJIM, WARASALI, KOSYOF]"
27,mat_doc,12392,0,430737,0.0,10.0,"[, 5003318671, 5000024578, 5000023477, 5003964471, 5002637267, 5002227238, 5001677070, 5002538095, 5001074857]"
28,mat_item,33,0,0,4.0,4.0,"[0000, 0001, 0002, 0003, 0004, 0005, 0006, 0007, 0008, 0009]"
29,ausvn,5507,0,0,8.0,8.0,"[00000000, 20141201, 20160113, 20100106, 20101109, 20120905, 20151124, 20140530, 20100722, 20141119]"
30,ausbs,1794,0,0,8.0,8.0,"[00000000, 20060502, 20040924, 20060112, 20060315, 20050511, 20060113, 20051111, 20060221, 20060110]"
31,pur_group,757,0,236234,0.0,3.0,"[, 891, 627, 983, 608, 015, 616, 311, 714, 008]"
32,bic_zserial,43644,0,377794,0.0,18.0,"[, 000000000000000001, 000000000000000002, 000000000000000003, 000000000000000004, 000000000000000005, 000000000000000006, 000000000000000008, 000000000000000007, NS-1]"
33,auztv,62225,0,0,6.0,6.0,"[000000, 163338, 143736, 132842, 102135, 110846, 101724, 093641, 080000, 072734]"
34,auztb,955,0,0,6.0,6.0,"[000000, 150000, 160000, 120000, 180000, 100000, 170000, 143000, 140000, 200000]"
35,bic_zrev_lvl,98,0,57044,0.0,2.0,"[A, B, C, , D, E, F, G, H, -]"
36,project,5490,0,772,0.0,24.0,"[R9997, SSRG10AR, R6128, SSRPRS1R, SSRBCP2R, SSRPRT1L, SSRG0T1L, SSRMFA1R, ARSH02, SSK10002]"
37,bic_zdt_osno,5684,0,0,8.0,8.0,"[20100107, 20141201, 20160113, 20120905, 20130108, 20101109, 20151124, 20141119, 20100722, 20111214]"
38,bic_zdt_nopr,5318,0,0,8.0,8.0,"[00000000, 20080611, 20120905, 20120827, 20140528, 20151124, 20150415, 20151015, 20160113, 20140610]"
39,bic_ztm_osno,74602,0,0,6.0,6.0,"[104533, 130521, 084336, 141104, 181930, 124708, 194453, 195440, 085144, 155236]"
40,bic_ztm_nopr,67857,0,0,6.0,6.0,"[000000, 195635, 130521, 094235, 180845, 124606, 163858, 125246, 144234, 133754]"

In [8]:
%%execsql

CREATE OR REPLACE FUNCTION my_to_date(text, text) RETURNS date AS $$

BEGIN
    IF to_number($1,'99999999') = 0 THEN
        RETURN null;
    ELSE 
        RETURN to_date($1, $2);
    END IF;
END;

$$ LANGUAGE plpgsql

In [9]:
%%showsql
select notificatn, nfcat_code, nfcat_grp, purch_org, vendor, salesorg, division, customer, funct_loc, equipment, material, plant,
my_to_date(bic_cqncpldat, 'YYYYMMDD') as bic_cqncpldat, oi_ebeln, oi_ebelp, not_type, base_uom, rstt_ftime, tctlstchg, 
bic_zprodord, mat_doc, mat_item, my_to_date(ausvn, 'YYYYMMDD') as ausvn, my_to_date(ausbs, 'YYYYMMDD') as ausbs, 
pur_group, auztv, auztb, bic_zrev_lvl, project, my_to_date(bic_zdt_osno, 'YYYYMMDD') as bic_zdt_osno, project, 
my_to_date(bic_zdt_nopr, 'YYYYMMDD') as bic_zdt_nopr, bic_ztm_osno, bic_ztm_nopr
from sap_bi.bic_azqn_o30400_int limit 10;

,notificatn,nfcat_code,nfcat_grp,purch_org,vendor,salesorg,division,customer,funct_loc,equipment,material,plant,bic_cqncpldat,oi_ebeln,oi_ebelp,not_type,base_uom,rstt_ftime,tctlstchg,bic_zprodord,mat_doc,mat_item,ausvn,ausbs,pur_group,auztv,auztb,bic_zrev_lvl,project,bic_zdt_osno,project,bic_zdt_nopr,bic_ztm_osno,bic_ztm_nopr
0,000200434342,0020,QI000015,,,,,,,,000000000573453002,1201,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-03-26,None,,111718,000000,00,R9997,2015-03-26,R9997,None,111747,000000
1,000200481612,0010,QE000015,,0000003023,,,,,,P6000127558,KOS1,None,,00000,ZE,EA,000000,20160128093544,,,0000,2016-01-28,None,,080346,000000,A,,2016-01-28,,None,080327,000000
2,000200434645,0050,QI000015,,,,,,,,P1000108406,EWHG,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-03-27,None,,091345,000000,B,R9997,2015-03-27,R9997,None,152103,000000
3,000200435140,0040,QI000015,,,,,,,,000000000000251183,1201,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-04-01,None,,084905,000000,C,R9997,2015-04-01,R9997,None,084934,000000
4,000200435411,0040,QI000015,,,,,,,,LA100-RK,1201,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-04-02,None,,094107,000000,J,R9997,2015-04-02,R9997,None,094144,000000
5,000200435872,0020,QI000015,,,,,,,,15083 F,1201,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-04-07,None,,110223,000000,O,R9997,2015-04-07,R9997,None,110255,000000
6,000200435884,0070,QI000015,,,,,,,,24121051019A,ESML,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-04-07,None,,130949,000000,B,R9997,2015-04-07,R9997,None,133828,000000
7,000200437110,0090,QI000015,,,,,,,,P1000087078,7330,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-04-14,None,,095523,000000,A,R9997,2015-04-14,R9997,None,172430,000000
8,000200437459,0040,QI000015,,,,,,,,192521D,1201,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-04-16,None,,082804,000000,E,R9997,2015-04-16,R9997,None,082837,000000
9,000200437721,0090,QI000015,,,,,,,,P1000086877,7330,None,,00000,ZF,EA,000000,20151115065546,,,0000,2015-04-16,None,,131128,000000,B,R9997,2015-04-16,R9997,None,201835,000000